### ISSUE TITLE
TypeError: require(...).load is not a function

### ISSUE THREAD

**Issue by Mrschabs** [Mrschabs/warbler#3]
I get the following error when running $node index.js 

C:\Users\Romano\warbler\warbler-server\middleware\auth.js:1
(function (exports, require, module, __filename, __dirname) { require("dotenv").load();
                                                                                ^

TypeError: require(...).load is not a function
    at Object.<anonymous> (C:\Users\Romano\warbler\warbler-server\middleware\auth.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Romano\warbler\warbler-server\index.js:9:46)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by Mrschabs** [comment]
changed .load() to .config()
re-ran npm install

**Comment by dewetblomerus** [comment]
@Mrschabs the way I knew to change to `config()` is by finding the instructions for the `dotenv` NPM package online and all the instructions talked about `config()`.

The way I knew to run `npm install` is when you had a package that you installed via NPM which your error said can't be found.

**Comment by SpeedSharma** [comment]
thanks it worked

**Comment by Antojoel** [comment]
.confg() works perfect

**Comment by adriancll** [comment]
thanks
